### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by yackermann** [AlexanderNZ/socomd-azure#1]
Yo @AlexanderNZ ! Just woundering, since I was playing with azure my self, have you tried digitalocean? They have way better prices then azure_) 
https://www.digitalocean.com/pricing/
Just thought about that_)

**Comment by finesseseth** [comment]
Heya, yeah i've used digitalocean before, our new teamspeak is hosted on
one of their boxes, vultr have similar pricing and also aussie boxes.

Seth

**Comment by yackermann** [comment]
@finesseseth thanks for vultr. That is awesome that they have aussia boxes. Will need for couple of future project.
@AlexanderNZ How is it going anyway?

**Comment by yackermann** [comment]
@finesseseth 
Couple of annoying things I found in their FAQ

> Do you allow outbound SMTP?
> Outbound SMTP is blocked by default. To lift this restriction, you must contact our support team and fill out an authorization form.

Why would you block SMTP?

> Do you charge for stopped instances?
> Yes, instances in a stopped state continue to reserve dedicated system resources (RAM, SSD storage, IP aliases, CPU) and therefore incur charges until you destroy the instance. If you wish to no longer 
> accumulate charges for a virtual machine, please use the DESTROY button in the customer portal.

~~DO does not charge for not running instances.~~
Ok it does. LOL. Should probably use them for calculating pi rather then them standing doing nothing.
